###
# String FM Synth - with phase wrapping (it does not change behaviour)
# PATCH NAME: STRINGS 1
# 14->3->1->1 |
#        1->1 |->out
#
#
# Flute FM Synth - with phase wrapping (it does not change behaviour)
# PATCH NAME: FLUTE 1
#    1.5->2->|
#      2->1->|
#         1->|->1->out
#
#
# Brass FM Synth - with phase wrapping (it does not change behaviour)
# PATCH NAME: BRASS 3
# 8.5->3.2->1->|
#           1->|
#           1->|->1->out
#
#
###

preprocess:
  sampling_rate:  &samplingrate  32000
  signal_length:  &signallength 128000
  block_size:     &blocksize 320
  conf_threshold: 0.85
  out_dir: ./preprocessed/
  data_location:  /home/teaonly/dataset/CINSTR/dizi
  extension: "wav"

model:
  sampling_rate: *samplingrate
  block_size: *blocksize
 
  input_hop:  4
  input_length: &inputlength 80
  hidden_size:  256
  
  FM_sync:  "FLUTE"
  FM_config: [1.5, 2.0, 2.0, 1.0, 1.0, 1.0]
  FM_amp:  3.0
  noise_bands: 65
  reverb_length: 1024

train:
  scales:   [ 8192,   4096,   2048,  1024,  512,   256,  128]
  weights:  [ 1.0,    1.0,    1.0,   1.0,   1.0,   1.0,  1.0]
  overlap:  0.75
